/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fredyprojectofinal;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JFrame;

/**
 *
 * @author janet
 */
public class FredyProjectoFinal extends javax.swing.JFrame {

    /**
     * Creates new form FredyProjectoFinal
     */
    public FredyProjectoFinal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        jMenuItem1 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        betText = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        cantPagar = new javax.swing.JTextField();
        pagar = new javax.swing.JButton();
        bljk = new javax.swing.JButton();
        slots = new javax.swing.JButton();
        horse = new javax.swing.JButton();
        salirGame = new javax.swing.JButton();
        bet = new javax.swing.JButton();
        endText = new javax.swing.JLabel();
        exchange = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        hit = new javax.swing.JButton();
        stand = new javax.swing.JButton();
        dealer = new javax.swing.JLabel();
        player = new javax.swing.JLabel();
        slotPanel1 = new javax.swing.JPanel();
        slot1 = new javax.swing.JLabel();
        slotPanel2 = new javax.swing.JPanel();
        slot2 = new javax.swing.JLabel();
        slotPanel3 = new javax.swing.JPanel();
        slot3 = new javax.swing.JLabel();
        slotPanel = new javax.swing.JPanel();
        roll = new javax.swing.JButton();
        cabDeci = new javax.swing.JTextField();
        cab1 = new javax.swing.JLabel();
        cab2 = new javax.swing.JLabel();
        cab3 = new javax.swing.JLabel();
        cab4 = new javax.swing.JLabel();
        cabBet = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Juegos");
        jButton1.setName(""); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 70, -1, -1));

        jButton2.setText("Pagar Deuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        betText.setToolTipText("Cambia tu apuesta");
        getContentPane().add(betText, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 111, 130, -1));

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 17, 72, 16));

        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 17, 72, 16));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 17, 72, 16));

        jButton3.setText("Trabajar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        cantPagar.setToolTipText("Inserte Cantidad Aqui");
        getContentPane().add(cantPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 245, 105, 41));

        pagar.setText("Pagar");
        pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarActionPerformed(evt);
            }
        });
        getContentPane().add(pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 292, -1, -1));

        bljk.setText("Blackjack");
        bljk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bljkActionPerformed(evt);
            }
        });
        getContentPane().add(bljk, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        slots.setText("Slots");
        slots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slotsActionPerformed(evt);
            }
        });
        getContentPane().add(slots, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        horse.setText("Caballos");
        horse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horseActionPerformed(evt);
            }
        });
        getContentPane().add(horse, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        salirGame.setText("Fin juego");
        salirGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirGameActionPerformed(evt);
            }
        });
        getContentPane().add(salirGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));

        bet.setText("Bet");
        bet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betActionPerformed(evt);
            }
        });
        getContentPane().add(bet, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 143, -1, -1));

        endText.setText("Has pagado tu deuda! Puedes salir.");
        endText.setToolTipText("");
        getContentPane().add(endText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 190, -1));

        exchange.setText("Canjear");
        exchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exchangeActionPerformed(evt);
            }
        });
        getContentPane().add(exchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 389));

        hit.setText("Hit");
        hit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitActionPerformed(evt);
            }
        });
        getContentPane().add(hit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        stand.setText("Stand");
        stand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standActionPerformed(evt);
            }
        });
        getContentPane().add(stand, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        dealer.setText("Dealer: ");
        getContentPane().add(dealer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 110, -1));

        player.setText("Player:");
        getContentPane().add(player, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 110, -1));

        javax.swing.GroupLayout slotPanel1Layout = new javax.swing.GroupLayout(slotPanel1);
        slotPanel1.setLayout(slotPanel1Layout);
        slotPanel1Layout.setHorizontalGroup(
            slotPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slot1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        slotPanel1Layout.setVerticalGroup(
            slotPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, slotPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(slot1, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(slotPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 40, 30));

        javax.swing.GroupLayout slotPanel2Layout = new javax.swing.GroupLayout(slotPanel2);
        slotPanel2.setLayout(slotPanel2Layout);
        slotPanel2Layout.setHorizontalGroup(
            slotPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slot2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        slotPanel2Layout.setVerticalGroup(
            slotPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, slotPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(slot2, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(slotPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 40, 30));

        javax.swing.GroupLayout slotPanel3Layout = new javax.swing.GroupLayout(slotPanel3);
        slotPanel3.setLayout(slotPanel3Layout);
        slotPanel3Layout.setHorizontalGroup(
            slotPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slot3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        slotPanel3Layout.setVerticalGroup(
            slotPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, slotPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(slot3, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(slotPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 40, 30));

        slotPanel.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout slotPanelLayout = new javax.swing.GroupLayout(slotPanel);
        slotPanel.setLayout(slotPanelLayout);
        slotPanelLayout.setHorizontalGroup(
            slotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        slotPanelLayout.setVerticalGroup(
            slotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(slotPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 160, 50));

        roll.setText("Roll");
        roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollActionPerformed(evt);
            }
        });
        getContentPane().add(roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 80, -1));

        cabDeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cabDeciActionPerformed(evt);
            }
        });
        getContentPane().add(cabDeci, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 80, -1));

        cab1.setText("Caballo 1");
        getContentPane().add(cab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        cab2.setText("Caballo 2");
        getContentPane().add(cab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        cab3.setText("Caballo 3");
        getContentPane().add(cab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, -1, -1));

        cab4.setText("Caballo 4");
        getContentPane().add(cab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, -1, -1));

        cabBet.setText("Start");
        getContentPane().add(cabBet, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
        static Random rand = new Random();
        
        
        static player  plr = new player(500, 5000, 0);
    
        static int moneybet = 0;
        
        static int deaer = 0;
        static int plaer = 0;
        
        static boolean blk = false;
        static boolean slo = false;
        static boolean hor = false;
        
        static int[] horses = new int[4];
        
        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (plr.getDinero() >= 100){
            bljk.setVisible(true);
            slots.setVisible(true);
            horse.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (plr.getDinero() > 100){
                cantPagar.setVisible(true);
                pagar.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        plr.setDinero(plr.getDinero()+100);
        updPlr();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarActionPerformed
        // TODO add your handling code here:
        if (cantPagar.getText().equalsIgnoreCase("cheat")){
            plr.setDinero(9999);
            plr.setChips(300);
            updPlr();
        }
        else{
            plr.setDeuda(plr.getDeuda()- Integer.parseInt(cantPagar.getText()));
            plr.setDinero(plr.getDinero()- Integer.parseInt(cantPagar.getText()));

            cantPagar.setVisible(false);
            pagar.setVisible(false);

            if (plr.getDeuda() <= 0 ){
                plr.setDeuda(0);
                salir.setVisible(true);
                endText.setVisible(true);
            }

            updPlr();
        }
    }//GEN-LAST:event_pagarActionPerformed

    private void bljkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bljkActionPerformed
        // TODO add your handling code here:
        bljk.setVisible(false);
        slots.setVisible(false);
        horse.setVisible(false);
        
        betText.setVisible(true);
        bet.setVisible(true);
        
        salirGame.setVisible(true);
        
        blk = true;
        
    }//GEN-LAST:event_bljkActionPerformed

    private void slotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slotsActionPerformed
        // TODO add your handling code here:
        bljk.setVisible(false);
        slots.setVisible(false);
        horse.setVisible(false);
        salirGame.setVisible(true);
        betText.setVisible(true);
        bet.setVisible(true);
        
        slo = true;
        
    }//GEN-LAST:event_slotsActionPerformed

    private void horseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horseActionPerformed
        // TODO add your handling code here:
        bljk.setVisible(false);
        slots.setVisible(false);
        horse.setVisible(false);
        salirGame.setVisible(true);        
        betText.setVisible(true);
        bet.setVisible(true);
        
        hor = true;
        
    }//GEN-LAST:event_horseActionPerformed

    private void salirGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirGameActionPerformed
        // TODO add your handling code here:
        
        bljk.setVisible(false);
        slots.setVisible(false);
        horse.setVisible(false);
        salirGame.setVisible(false);
        betText.setVisible(false);
        bet.setVisible(false);
        
        hit.setVisible(false);
        stand.setVisible(false);
        player.setVisible(false);
        dealer.setVisible(false);
        
        roll.setVisible(false);
        slotPanel.setVisible(false);
        slotPanel1.setVisible(false);
        slotPanel2.setVisible(false);
        slotPanel3.setVisible(false);
        slot1.setVisible(false);
        slot2.setVisible(false);
        slot3.setVisible(false);
        
        cab1.setVisible(false);
                cab2.setVisible(false);
                cab3.setVisible(false);
                cab4.setVisible(false);
                cabDeci.setVisible(false);
                cabBet.setVisible(false);
        
        blk = false;
        slo = false;
        hor = false;
        
    }//GEN-LAST:event_salirGameActionPerformed

    private void betActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betActionPerformed
        // TODO add your handling code here:
        
        if (blk == true && Integer.parseInt(betText.getText()) > 0){
            hit.setVisible(true);
            stand.setVisible(true);
            player.setVisible(true);
            dealer.setVisible(true);
            deaer += rand.nextInt(1,11);
            
            moneybet = Integer.parseInt(betText.getText());
            plr.setDinero(plr.getDinero() - moneybet);
            updPlr();
            bljkUpd();
        }
        else if (slo == true && Integer.parseInt(betText.getText()) > 0){
            slotPanel.setVisible(true);
                slotPanel1.setVisible(true);
                slotPanel2.setVisible(true);
                slotPanel3.setVisible(true);
                slot1.setVisible(true);
                slot2.setVisible(true);
                slot3.setVisible(true);
                roll.setVisible(true);
            
                moneybet = Integer.parseInt(betText.getText());
            plr.setDinero(plr.getDinero() - moneybet);
            updPlr();    
            
            
        }
        else if (hor == true && Integer.parseInt(betText.getText()) > 0){
            
        }
    }//GEN-LAST:event_betActionPerformed

    private void exchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exchangeActionPerformed
        // TODO add your handling code here:
        boolean hasChips = true;
        
        chipConv();
        
        updPlr();
    }//GEN-LAST:event_exchangeActionPerformed

    private void hitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitActionPerformed
        // TODO add your handling code here:
        
        plaer += rand.nextInt(0,11);
        
        bljkUpd();
        
        if(plaer > 21){
            updPlr();
            hit.setVisible(false);
            stand.setVisible(false);
        }
        
    }//GEN-LAST:event_hitActionPerformed

    private void standActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standActionPerformed
        // TODO add your handling code here:
        
        deaer += rand.nextInt(5,11);
        bljkUpd();
        if (deaer == 21){
            updPlr();
            hit.setVisible(false);
            stand.setVisible(false);
        }
        else if(plaer == 21){
            plr.setChips(plr.getChips() + (moneybet * 3));
            updPlr();
            hit.setVisible(false);
            stand.setVisible(false);
        }
        else if(deaer > 21 && plaer < 21){
            plr.setChips(plr.getChips() + moneybet);
            updPlr();
            hit.setVisible(false);
            stand.setVisible(false);
        }
        else if(plaer > deaer){
            plr.setChips(plr.getChips() + moneybet);
            updPlr();
            hit.setVisible(false);
            stand.setVisible(false);
        }
        else{
            updPlr();
            hit.setVisible(false);
            stand.setVisible(false);
        }
    }//GEN-LAST:event_standActionPerformed

    private void rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollActionPerformed
        // TODO add your handling code here:
        
        if (Integer.parseInt(betText.getText()) < plr.getDinero()){
            
            plr.setDinero(plr.getDinero() - moneybet);
            
            int roll1 = rand.nextInt(0,12);
            int roll2 = rand.nextInt(0,12);   
            int roll3 = rand.nextInt(0,12);
            
            slot1.setText(Integer.toString(roll1));
            slot2.setText(Integer.toString(roll2));
            slot3.setText(Integer.toString(roll3));
            
            if(roll1 == 7 && roll2 == 7 && roll3 == 7 ){
                plr.setChips(plr.getChips() + (moneybet * 7));
            }
            else if (roll1 == roll2 || roll2 == roll3 || roll3 == roll1){
                plr.setChips(plr.getChips() + (moneybet * 3));
            }
            updPlr();
        }
        else{
            roll.setVisible(false);
            updPlr();
        }
        
        
    }//GEN-LAST:event_rollActionPerformed

    private void cabDeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cabDeciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cabDeciActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FredyProjectoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FredyProjectoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FredyProjectoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FredyProjectoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>*/
        
        
        
                
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FredyProjectoFinal().setVisible(true);
                
                cantPagar.setVisible(false);
                pagar.setVisible(false);
                betText.setVisible(false);
                bet.setVisible(false);
                
                bljk.setVisible(false);
                slots.setVisible(false);
                horse.setVisible(false);
                salirGame.setVisible(false);
                
                salir.setVisible(false);
                endText.setVisible(false);
                
                hit.setVisible(false);
                stand.setVisible(false);
                player.setVisible(false);
                dealer.setVisible(false);
                
                roll.setVisible(false);
                slotPanel.setVisible(false);
                slotPanel1.setVisible(false);
                slotPanel2.setVisible(false);
                slotPanel3.setVisible(false);
                slot1.setVisible(false);
                slot2.setVisible(false);
                slot3.setVisible(false);
                
                cab1.setVisible(false);
                cab2.setVisible(false);
                cab3.setVisible(false);
                cab4.setVisible(false);
                cabDeci.setVisible(false);
                cabBet.setVisible(false);
                
                updPlr();
            }
        });
        
 
        
    }
       public static void updPlr(){
                jLabel1.setText("Dinero: " + Integer.toString(plr.getDinero()));
                jLabel2.setText("Deuda: " + Integer.toString(plr.getDeuda()));
                jLabel3.setText("Chips: " + Integer.toString(plr.getChips()));
    }
       
       public static boolean chipConv(){
           if (plr.getChips()<30){
               return false;
           }
           else{
               plr.setDinero(plr.getDinero() + 30);
               plr.setChips(plr.getChips() - 30);
               return chipConv();
           }
           
           
       }
       
       
       
       
      
       public static void bljkUpd(){
           dealer.setText("Dealer: " + deaer);
           player.setText("Player: " + plaer);
           
       }
       
       public static void exit(){
           bljk.setVisible(false);
            slots.setVisible(false);
            horse.setVisible(false);
            salirGame.setVisible(false);
            betText.setVisible(false);
            bet.setVisible(false);

            hit.setVisible(false);
            stand.setVisible(false);
            player.setVisible(false);
            dealer.setVisible(false);


            blk = false;
            slo = false;
            hor = false;
       }
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton bet;
    private static javax.swing.JFormattedTextField betText;
    private static javax.swing.JButton bljk;
    private static javax.swing.JLabel cab1;
    private static javax.swing.JLabel cab2;
    private static javax.swing.JLabel cab3;
    private static javax.swing.JLabel cab4;
    private static javax.swing.JButton cabBet;
    private static javax.swing.JTextField cabDeci;
    private static javax.swing.JTextField cantPagar;
    private static javax.swing.JLabel dealer;
    private static javax.swing.JLabel endText;
    private javax.swing.JButton exchange;
    private static javax.swing.JButton hit;
    private static javax.swing.JButton horse;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private static javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabel2;
    private static javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JButton pagar;
    private static javax.swing.JLabel player;
    private static javax.swing.JButton roll;
    private static javax.swing.JButton salir;
    private static javax.swing.JButton salirGame;
    private java.awt.ScrollPane scrollPane1;
    private static javax.swing.JLabel slot1;
    private static javax.swing.JLabel slot2;
    private static javax.swing.JLabel slot3;
    private static javax.swing.JPanel slotPanel;
    private static javax.swing.JPanel slotPanel1;
    private static javax.swing.JPanel slotPanel2;
    private static javax.swing.JPanel slotPanel3;
    private static javax.swing.JButton slots;
    private static javax.swing.JButton stand;
    // End of variables declaration//GEN-END:variables
}
